### ISSUE TITLE
Discussion: Milestone 0 Discussion of evm on wasm decision

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/fvm-project#38]
Let's use this issue to discuss our decision to support evm on wasm decision:
- What's working
- What's different
- Any changes to our assumptions
- Outstanding items left to validate
- RESULT (go/nogo on supporting evm)

**Comment by raulk** [comment]
Just to add to @Stebalien, we now have a detailed EVM <> FVM mapping spec (#39) which dives into the mechanics of how the EVM on WASM will operate. SputnikVM does appear to expose the hooks we need, embodied in the concept of the "handler". And we've also been pointed out at a new Rust EVM implementation here that we'll consider adopting and supporting: https://github.com/bluealloy/revm.

**Comment by shibowe** [comment]
> Just to add to @Stebalien, we now have a detailed EVM <> FVM mapping spec (#39) which dives into the mechanics of how the EVM on WASM will operate. SputnikVM does appear to expose the hooks we need, embodied in the concept of the "handler". And we've also been pointed out at a new Rust EVM implementation here that we'll consider adopting and supporting: https://github.com/bluealloy/revm.

looks like the REVM might be better than SputnikVM, and according to the features --> " interfacing - [no_std] so that it can be used as wasm lib and integrate with JavaScript and cpp binding if needed."
